# Generated by Django 2.2.17 on 2021-02-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
        migrations.AlterModelOptions(
            name='worksmetadata',
            options={'verbose_name_plural': 'Works Metadata'},
        ),
    ]
